version: '3'


services:
  mysql8:
    container_name: mysql8
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      # MySQL 官方镜像会在容器启动时，自动执行 /docker-entrypoint-initdb.d 文件夹下的 SQL 脚本，从而完成数据库初始化
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      # 注意，映射为了 13316 端口
      - "3306:3306"

  redis:
    container_name: redis
    image: 'bitnami/redis:7.2'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
